# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd68d32ad0e4860395c076d132e8735ed41082bbe8f1c17ca6faf6dc943b620ee954765945198c615404f986a2f03fcfd27bc29cf00dc76bda6cf6452d443d0d

test:
  secret_key_base: 7a969e58f50e505a1f85a8d513ae71e6a0ae3c8160e6632c5e85a8dc1dbcb1cd3d8dd922de67cffda5a2582f603342796d68176eeaff496e8a25ee9bce3aae62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
